### ISSUE TITLE
README has an error

### ISSUE THREAD

**Issue by mjwall** [crate/crate-java-testing#46]
If you follow the readme, it tells you to add this to your pom
```
<repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray</name>
        <url>http://dl.bintray.com/crate/crate</url>
    </repository>
```
However because the id is central, it replaces the definition of the main repo at https://repo.maven.apache.org/maven2 and then maven can't find dependencies like commons-compress.  Better to use a different string for the id, like "bintray" so it actually adds instead of replaces

**Comment by matriv** [comment]
Fixed. Thanks for reporting @mjwall!
