### ISSUE TITLE
execute needs update for crate 3.0.0

### ISSUE THREAD

**Issue by mjwall** [crate/crate-java-testing#48]
Build crate from master to test fix for https://github.com/crate/crate/issues/7185 and ran into 

java.io.IOException: Server returned HTTP response code: 406 for URL: http://127.0.0.1:4504/_sql

trying to execute("create blob table myblob")

Running curl gives more info

```
curl -sSPOST  "http://127.0.0.1:4504/_sql?pretty" -d '{"stmt":"create blob table myblob"}'
{
  "error" : "Content-Type header [application/x-www-form-urlencoded] is not supported",
  "status" : 406
}
```

Think this is a change in ElasticSearch.  Changing https://github.com/crate/crate-java-testing/blob/48609a8bd239a110776f84c1a82bd0d7affa395b/src/test/java/io/crate/integrationtests/BaseTest.java#L65 to application/json fixes it

**Comment by matriv** [comment]
@mjwall Fix is merged and available in `0.6.2`

Thanks for reporting!
